package com.appzonegroup.creditclub.pos.util;

import org.jpos.iso.*;

/**
 * Created by mac on 1/29/19.
 */

public class ISO87BPackager extends ISOBasePackager {
    private static final boolean pad = false;
    protected ISOFieldPackager fld[] = {
            /* 000 */ new IFA_NUMERIC(4, "Message Type Indicator"),
            /* 001 */ new IFA_BITMAP(32, "Bitmap"),
            /* 002 */ new IFA_LLCHAR(19, "PAN - PRIMARY ACCOUNT NUMBER"),
            /* 003 */ new IFA_NUMERIC(6, "Processing Code"),
            /* 004 */ new IFA_NUMERIC(12, "Amount, Transaction"),
            /* 005 */ new IFA_NUMERIC(12, "Amount, Reconciliation"),
            /* 006 */ new IFA_NUMERIC(12, "Amount, Cardholder billing"),
            /* 007 */ new IFA_NUMERIC(10, "Date and time, transmission"),
            /* 008 */ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", false),
            /* 009 */ new IFB_NUMERIC(8, "Conversion rate, Reconciliation", false),
            /* 010 */ new IFA_NUMERIC(8, "Conversion rate, Cardholder billing"),
            /* 011 */ new IFA_NUMERIC(6, "System trace audit number"),
            /* 012 */ new IFA_NUMERIC(6, "Time, local transaction"),
            /* 013 */ new IFA_NUMERIC(4, "Date, local transaction"),
            /* 014 */ new IFA_NUMERIC(4, "Date, expiration"),
            /* 015 */ new IFA_NUMERIC(4, "Date, Settlement"),
            /* 016 */ new IFA_NUMERIC(4, "Date, Conversion"),
            /* 017 */ new IFA_NUMERIC(4, "Date, Capture"),
            /* 018 */ new IFA_NUMERIC(4, "Merchant Type"),
            /* 019 */ new IFA_NUMERIC(3, "ACQUIRING INSTITUTION COUNTRY CODE"),
            /* 020 */ new IFA_NUMERIC(3, "PAN EXTENDED COUNTRY CODE"),
            /* 021 */ new IFA_NUMERIC(3, "FORWARDING INSTITUTION COUNTRY CODE"),
            /* 022 */ new IFA_NUMERIC(3, "POINT OF SERVICE ENTRY MODE"),
            /* 023 */ new IFA_NUMERIC(3, "CARD SEQUENCE NUMBER"),
            /* 024 */ new IFA_NUMERIC(3, "NETWORK INTERNATIONAL IDENTIFIER"),
            /* 025 */ new IFA_NUMERIC(2, "POINT OF SERVICE CONDITION CODE"),
            /* 026 */ new IFA_NUMERIC(2, "POINT OF SERVICE PIN CAPTURE CODE"),
            /* 027 */ new IFA_NUMERIC(1, "AUTHORIZATION IDENTIFICATION RESP LEN"),
            /* 028 */ new IFA_AMOUNT(9, "AMOUNT, TRANSACTION FEE"),
            /* 029 */ new IFA_AMOUNT(9, "AMOUNT, SETTLEMENT FEE"),
            /* 030 */ new IFA_AMOUNT(9, "AMOUNT, TRANSACTION PROCESSING FEE"),
            /* 031 */ new IFA_AMOUNT(9, "AMOUNT, SETTLEMENT PROCESSING FEE"),
            /* 032 */ new IFA_LLCHAR(11, "ACQUIRING INSTITUTION IDENT CODE"),
            /* 033 */ new IFA_LLCHAR(11, "FORWARDING INSTITUTION IDENT CODE"),
            /* 034 */ new IFA_LLCHAR(28, "PAN EXTENDED"),
            /* 035 */ new IFA_LLCHAR(39, "TRACK 2 DATA"),
            /* 036 */ new IFA_LLLCHAR(104, "TRACK 3 DATA"),
            /* 037 */ new IF_CHAR(12, "RETRIEVAL REFERENCE NUMBER"),
            /* 038 */ new IF_CHAR(6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
            /* 039 */ new IF_CHAR(2, "RESPONSE CODE"),
            /* 040 */ new IF_CHAR(3, "SERVICE RESTRICTION CODE"),
            /* 041 */ new IF_CHAR(8, "CARD ACCEPTOR TERMINAL IDENTIFICACION"),
            /* 042 */ new IF_CHAR(15, "CARD ACCEPTOR IDENTIFICATION CODE"),
            /* 043 */ new IF_CHAR(40, "CARD ACCEPTOR NAME/LOCATION"),
            /* 044 */ new IFA_LLCHAR(25, "ADITIONAL RESPONSE DATA"),
            /* 045 */ new IFA_LLCHAR(76, "TRACK 1 DATA"),
            /* 046 */ new IFA_LLLCHAR(999, "ADDITIONAL DATA - ISO"),
            /* 047 */ new IFA_LLLCHAR(999, "ADITIONAL DATA - NATIONAL"),
            /* 048 */ new IFA_LLLCHAR(999, "ADITIONAL DATA - PRIVATE"),
            /* 049 */ new IF_CHAR(3, "CURRENCY CODE, TRANSACTION"),
            /* 050 */ new IF_CHAR(3, "CURRENCY CODE, SETTLEMENT"),
            /* 051 */ new IF_CHAR(3, "CURRENCY CODE, CARDHOLDER BILLING"),
            /* 052 */ new IFA_NUMERIC(16, "PIN DATA"),
            /* 053 */ new IFB_LLHECHAR(96, "SECURITY RELATED CONTROL INFORMATION"),
            /* 054 */ new IFA_LLLCHAR(120, "ADDITIONAL AMOUNTS"),
            /* 055 */ new IFA_LLLCHAR(510, "RESERVED ISO"),
            /* 056 */ new IFA_LLCHAR(4, "RESERVED ISO"),
            /* 057 */ new IFA_LLLCHAR(999, "RESERVED ISO"),
            /* 058 */ new IFA_LLLCHAR(11, "RESERVED ISO"),
            /* 059 */ new IFA_LLLCHAR(255, "RESERVED ISO"),
            /* 060 */ new IFA_LLLCHAR(999, "RESERVED ISO"),
            /* 061 */ new IFA_LLLCHAR(999, "RESERVED ISO"),
            /* 062 */ new IFA_LLLCHAR(999, "RESERVED PRIVATE"),
            /* 063 */ new IFA_LLLLCHAR(9999, "RESERVED ISO"),
            /* 064 */ new IFA_LLCHAR(64, "Message Authentication Code Field"),
            /* 065 */ new IFA_NUMERIC(1, "BITMAP, EXTENDED"),
            /* 066 */ new IFA_NUMERIC(1, "SETTLEMENT CODE"),
            /* 067 */ new IFA_NUMERIC(2, "EXTENDED PAYMENT CODE"),
            /* 068 */ new IFA_NUMERIC(3, "RECEIVING INSTITUTION COUNTRY CODE"),
            /* 069 */ new IFA_NUMERIC(3, "SETTLEMENT INSTITUTION COUNTRY CODE"),
            /* 070 */ new IFA_NUMERIC(3, "NETWORK MANAGEMENT INFORMATION CODE"),
            /* 071 */ new IFA_NUMERIC(4, "MESSAGE NUMBER"),
            /* 072 */ new IFA_NUMERIC(4, "MESSAGE NUMBER LAST"),
            /* 073 */ new IFA_NUMERIC(6, "DATE ACTION"),
            /* 074 */ new IFA_NUMERIC(10, "CREDITS NUMBER"),
            /* 075 */ new IFA_NUMERIC(10, "CREDITS REVERSAL NUMBER"),
            /* 076 */ new IFA_NUMERIC(10, "DEBITS NUMBER"),
            /* 077 */ new IFA_NUMERIC(10, "DEBITS REVERSAL NUMBER"),
            /* 078 */ new IFA_NUMERIC(10, "TRANSFER NUMBER"),
            /* 079 */ new IFA_NUMERIC(10, "TRANSFER REVERSAL NUMBER"),
            /* 080 */ new IFA_NUMERIC(10, "INQUIRIES NUMBER"),
            /* 081 */ new IFA_NUMERIC(10, "AUTHORIZATION NUMBER"),
            /* 082 */ new IFA_NUMERIC(12, "CREDITS, PROCESSING FEE AMOUNT"),
            /* 083 */ new IFA_NUMERIC(12, "CREDITS, TRANSACTION FEE AMOUNT"),
            /* 084 */ new IFA_NUMERIC(12, "DEBITS, PROCESSING FEE AMOUNT"),
            /* 085 */ new IFA_NUMERIC(12, "DEBITS, TRANSACTION FEE AMOUNT"),
            /* 086 */ new IFA_NUMERIC(16, "CREDITS, AMOUNT"),
            /* 087 */ new IFA_NUMERIC(16, "CREDITS, REVERSAL AMOUNT"),
            /* 088 */ new IFA_NUMERIC(16, "DEBITS, AMOUNT"),
            /* 089 */ new IFA_NUMERIC(16, "DEBITS, REVERSAL AMOUNT"),
            /* 090 */ new IFA_NUMERIC(42, "ORIGINAL DATA ELEMENT"),
            /* 091 */ new IF_CHAR(1, "FILE UPDATE CODE"),
            /* 092 */ new IF_CHAR(2, "FILE SECURITY CODE"),
            /* 093 */ new IF_CHAR(6, "RESPONSE INDICATOR"),
            /* 094 */ new IF_CHAR(7, "SERVICE INDICATOR"),
            /* 095 */ new IF_CHAR(42, "REPLACEMENT AMOUNT"),
            /* 096 */ new IFA_BINARY(16, "MESSAGE SECURITY CODE"),
            /* 097 */ new IFA_AMOUNT(17, "AMOUNT, NET SETTLEMENT"),
            /* 098 */ new IF_CHAR(25, "PAYEE"),
            /* 099 */ new IFA_LLNUM(11, "SETTLEMENT INSTITUTION IDENT CODE"),
            /* 100 */ new IFA_LLNUM(11, "RECEIVING INSTITUTION IDENT CODE"),
            /* 101 */ new IFA_LLCHAR(17, "FILE NAME"),
            /* 102 */ new IFA_LLCHAR(28, "FROM ACCOUNT"),
            /* 103 */ new IFA_LLCHAR(28, "ACCOUNT IDENTIFICATION 2"),
            /* 104 */ new IFA_LLLCHAR(100, "TRANSACTION DESCRIPTION"),
            /* 105 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 106 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 107 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 108 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 109 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 110 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 111 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 112 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 113 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 114 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 115 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 116 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 117 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 118 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 119 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 120 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 121 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 122 */ new IFA_LLLCHAR(999, "RESERVED ISO USE"),
            /* 123 */ new IFA_LLLCHAR(18, "Reserved for private use"),
            /* 124 */ new IFA_LLLLCHAR(9999, "Reserved for private use"),
            /* 125 */ new IFB_LLLCHAR(999, "Reserved for private use"),
            /* 126 */ new IFB_LLLCHAR(999, "Reserved for private use"),
            /* 127 */ new IFB_LLLCHAR(999, "Reserved for private use"),
            /* 128 */ new IFA_LLCHAR(64, "Message authentication code field")
    };

    public ISO87BPackager() {
        super();
        setFieldPackager(fld);
    }
}