image: androidsdk/android-30

pipelines:
  default:
      - step:
          name: Android Staging Application
          caches:
            - gradle
          script:
            - ./gradlew assembleReleaseStaging
            - ./gradlew lint
          artifacts:
            - app/build/outputs/**
            - app/build/reports/**
