image: androidsdk/android-30

pipelines:
  default:
      - step:
          name: Cluster Staging Application
          deployment: staging
          caches:
            - gradle
          script:
            - echo "$SIGNING_JKS_FILE" | base64 -d > android-signing-keystore.jks
            - ./gradlew assembleHeritageReleaseStaging --no-daemon
          artifacts:
            - app/build/outputs/**
            - app/build/reports/**
      - step:
          name: Cluster Prod Application
          deployment: production
          caches:
            - gradle
          script:
            - echo "$SIGNING_JKS_FILE" | base64 -d > android-signing-keystore.jks
            - ./gradlew assembleRelease --no-daemon
          artifacts:
            - app/build/outputs/**
            - app/build/reports/**
